name: Deploy plugin assets to WordPress.org
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      PLUGIN_SLUG:
        description: WordPress.org plugin slug
        required: false
        type: string
    secrets:
      SVN_USERNAME:
        required: true
      SVN_PASSWORD:
        required: true

env:
  DEV_SCRIPTS_DIR: ${{ github.workspace }}/vendor/publishpress/dev-workspace/scripts

jobs:
  deploy-assets:
    name: Deploy plugin assets to WordPress.org
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up PHP
        # shivammathur/setup-php@2.37.0
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f
        with:
          php-version: 8.3
          extensions: mbstring,xml,curl,zip,intl,bcmath,gettext,mysqli,phar,gd,iconv,yaml
          tools: composer:v2

      - name: Read plugin metadata
        if: ${{ inputs.PLUGIN_SLUG == '' }}
        id: get-metadata
        run: |
          composer install --no-interaction --prefer-dist --no-progress || true
          composer deploy:metadata-github-output

      - name: Update WordPress.org plugin assets and readme
        # 10up/action-wordpress-plugin-asset-update@v2.2.0
        uses: 10up/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ inputs.PLUGIN_SLUG != '' && inputs.PLUGIN_SLUG || steps.get-metadata.outputs.plugin-folder }}
          IGNORE_OTHER_FILES: true
