name: Deploy plugin assets to WordPress.org
permissions:
  contents: read
on:
  workflow_call:

env:
  DEV_SCRIPTS_DIR: ${{ github.workspace }}/vendor/publishpress/dev-workspace/scripts

jobs:
  deploy-assets:
    name: Deploy plugin assets to WordPress.org
    runs-on: [self-hosted, release]
    steps:
        - name: Checkout code
          # actions/checkout@v6.0.2
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

        - name: Create root .env from template
          run: |
            cp $GITHUB_WORKSPACE/.env.example $GITHUB_WORKSPACE/.env

        - name: Validate composer.json
          run: composer validate

        - name: Install Composer dependencies
          run: composer install

        - name: Show dev-workspace tool versions
          run: composer info:version

        - name: Add dev-workspace scripts to PATH
          run: echo "$DEV_SCRIPTS_DIR" >> "$GITHUB_PATH"

        - name: Get the plugin version and metadata
          id: get-metadata
          run: |
            PLUGIN_SLUG=$(jq -r '.extra["plugin-slug"]' composer.json)
            PLUGIN_FOLDER=$(jq -r '.extra["plugin-folder"]' composer.json)
            PLUGIN_NAME=$(jq -r '.extra["plugin-name"]' composer.json)
            PLUGIN_VERSION=$(plugin-version.sh)
            echo "plugin_slug=${PLUGIN_SLUG}" >> "$GITHUB_OUTPUT"
            echo "plugin_folder=${PLUGIN_FOLDER}" >> "$GITHUB_OUTPUT"
            echo "plugin_name=${PLUGIN_NAME}" >> "$GITHUB_OUTPUT"
            echo "plugin_version=${PLUGIN_VERSION}" >> "$GITHUB_OUTPUT"

        - name: WordPress.org plugin asset/readme update
          # 10up/action-wordpress-plugin-asset-update@v2.2.0
          uses: 10up/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7
          env:
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SLUG: ${{ steps.get-metadata.outputs.plugin_slug }}
            IGNORE_OTHER_FILES: true
